
<dt>26/02/2009</dt>
<dd>Suite aux <a href="http://groups.google.com/group/fr.comp.infosystemes.www.auteurs/msg/fce26086705e7a6a">remarques de Olivier Miakinen</a>
et parce que le temps passe :), quelques corrections sur l'article <a href="info/inet/html_ou_xhtml.php">"HTML ou XHTML ?"</a>.
</dd>

<dt>22/02/2009</dt>
<dd>- suppression rubrique Copains<br>
- mise à jour CV
</dd>

<dt>08/08/2007</dt>
<dd>Ouf ! repris enfin un peu de temps pour ce site...<br>
- "anonymisé" mon CV<br>
- mis en ligne les premières ébauches des documents web & charset plus complets<br>
- terminé le document <a href="info/inet/ND_doctype.php">Notes/Domino et Doctype</a></dd>

<dt>19/12/2006</dt>
<dd>Quelques mini modifications de quelques rédactionnels...</dd>

<dt>21/12/2005, v6.0.0</dt>
<dd>On a été sacrément occupé par le <a href="http://www.pingmachine.org">site de Ping Machine</a>
ces dernier temps, mais ça y est... à peu près !<br>
- Rajouté en section musique un petit barratin sur moi, et des pointeurs vers les coups de coeur blogés sur Ping Machine<br>
- Lien vers le site de Ping Machine (encore) dans la page des liens
</dd>

<dt>22/09/2005</dt>
<dd>- Ajout de Laetitia & Martial dans la page des copains<br>
- Corrections des articles <a href="info/inet/html_ou_xhtml.php">"HTML ou XHTML ?"</a>,
<a href="info/i18n/outils.php">"i18n Outils & doc"</a> et
<a href="info/i18n/web_charset.php">"Web, codages et jeux de caractères"</a><br>
- modif de la CSS (en particulier prb sur les blockquote)<br></dd>

<dt>24/08/2005</dt>
<dd>Modifications d'importance de la feuille de style principale, en espérant
que les pages soient maintenant plus lisibles<br>
Passage en ligne de la 1ere version complète de <a href="info/inet/html_ou_xhtml.php">HTML ou XHTML ?</a><br>
Et toujours en informatique, un nouveau document : <a href="info/inet/css_grp.php">CSS groupement de déclarations</a></dd>

<dt>08/08/2005</dt>
<dd>1ere version non en travaux de <a href="info/i18n/web_charset.php">web et codages</a></dd>

<dt>05/08/2005</dt>
<dd>Pleins de petites maj depuis un moment... Ce soir en particulier : quelques
petits mots pour se présenter sur cette page, une rubrique informatique qui
se remplit doucement (et même quelques articles terminés !!), la section
liens qui évolue doucement, la page copains qui se complète (tout aussi
doucement... oui bon), et pleins d'idées pour la rubrique musique !</dd>

<dt>14/07/2005</dt>
<dd>Après quelques modifs très techniques (CSS, balises LINK, ...) ou
mineures tout au long de la semaine dernière, passage en ligne d'une version
finale (pour la mise en page uniquement, chaque chose en son temps...) de la
page <a href="copains/">les copains</a> (d'abord)</dd>

<dt>22/06/2005</dt>
<dd>- prb du lien vers l'accueil dans le menu corrigé<br>
- page d'erreur 404 personnalisée<br>
- maquette compil 2001<br>
- Mise en place de IE7</dd>

<dt>17/06/2005</dt>
<dd>Mise en place de la majorité des images titres manquantes (<q>alors ça, c'est fait !</q>)<br>
"Liens dans nouvelle fenêtre" en position:fixed</dd>

<dt>22/05/2005</dt>
<dd>1ere mise à jour avec <a href="http://www.lyra.org/sitecopy/">Sitecopy</a> !<br>
Quelques modifs dans la page de liens, dans l'accueil, et ajout de quelques
images de titres niveau 2.</dd>

<dt>16/05/2005</dt>
<dd>Page de liens presque finale...</dd>

<dt>07/05/05</dt>
<dd>Bon j'avoue, perdre tout ce que j'avais réalisé jusqu'à maintenant dans mon
crash disque... Ca ne m'a pas aidé à m'y remettre. Après plusieurs mois de mise
en silence, nous y revoilà !! On a la gniaaak !! Bon, pour l'instant ce n'est
que l'accueil qui est à peu près OK. Par contre, les anciens auront remarqué
que les entrées du menu ont changées... car j'ai pleins d'idées !! Aller, j'y
retourne :))</dd>

