<dt>12/10/2014, v7.9.5</dt>
<dd>
- accueil : modification du texte,<br>
- correction de la couleur des liens de la barre de navigation,<br>
- informatique / <a href="info/GEPApiR/css.php">CSS mises en forme diverses</a> :
complément sur la compatibilité navigateurs,<br>
- informatique / <a href="info/GEPApiR/menu_nav.php">Menu de navigation</a> : complément
sur la bordure,<br>
- informatique / <a href="info/inet/ND_doctype.php">Développement Notes / Domino et doctype HTML</a> :
maj suite à constatation que le DarkBlog n'est plus accessible
</dd>

<dt>02/09/2014, v7.8.1</dt>
<dd>
informatique / <a href="info/GEPApiR/responsive.php">responsive design</a> :<br>
- introduction plus complète,<br>
- ajout d'exemples sur les marges en %,<br>
- précision sur le border-radius du menu
</dd>

<dt>30/08/2014, v7.8.0</dt>
<dd>
- marges horizontales en %,<br>
- passage de l'arrondi du menu en % pour la composante horizontale,<br>
- informatique / <a href="info/GEPApiR/responsive.php">responsive design</a> :
mise à jour des captures du menu et de la fonction writeCSSRespImg(), ajout d'un
paragraphe sur les unités CSS relatives,<br>
- ajout de box-shadow, border-radius et border outset sur les blockquote
</dd>

<dt>29/08/2014, v7.7.5</dt>
<dd>
- ajout du gzip sur les pages du site,<br>
- minification et ajout du gzip sur la css et le javascript du site,<br>
- informatique / <a href="info/GEPApiR/performances.php">performances</a> : renommage de la page (anciennement CSS Sprites) et ajout d'info sur les autres techniques utilisées (concaténation, minification, gzip, ...),<br>
- ajout d'arrondis sur la bordure du menu,<br>
- ajout d'une marge sous les images des H1,<br>
- informatique / <a href="info/GEPApiR/css.php">mises en forme diverses</a> : compléments supplémentaires sur CSS Shapes,<br>
- informatique / <a href="info/inet/outils.php">outils pour le concepteur de site personnel</a> :
ajout d'outils de test responsive design,<br>
- mini corrections diverses dans des articles
</dd>

<dt>23/08/2014, v7.6.1</dt>
<dd>
- musiques : création d'<a href="zicmue/finale.php">une page sur Finale</a>,<br>
- informatique / <a href="info/GEPApiR/css.php">mises en forme diverses</a> : ajout de compléments sur CSS Shapes
</dd>

<dt>22/08/2014, v7.5.0</dt>
<dd>
- ajout d'un flux RSS sur le changelog,<br>
- informatique : fait disparaitre les articles pas encore prets,<br>
- informatique / <a href="info/i18n/web-charset_html.php">internationalisation pour le concepteur web</a> : mise à jour,<br>
- informatique / <a href="info/GEPApiR/responsive.php">responsive design</a> : compléments sur les attributs HTML 5 data-*
</dd>

<dt>15/08/2014, v7.4.3</dt>
<dd>
- informatique : ajout au besoin d'un système de TOC automatique (merci <a href="http://www.whitsoftdev.com/articles/toc.html">WhitSoftDev</a>),<br>
- informatique : ajout d'une sous rubrique "<a href="info/#GepapiR">La GepapiR côté technique</a>",<br>
- informatique : ajout d'une page <a href="info/inet/outils.php">outils</a> des
concepteurs de site personnel,<br>
- informatique / <a href="info/inet/css_grp.php">css groupement</a> : changement titre, ajout préproc et variables CSS,<br>
- informatique : mise en place des nouvelles footnotes,<br>
- bascule sur la web font <a href="https://www.google.com/fonts/specimen/Satisfy">Satisfy</a> chez <a href="https://www.google.com/fonts">Google fonts</a>, afin de profiter de leur CDN et polices optimisées !<br>
- moi : ajout d'un lien IMDB
</dd>

<dt>13/08/2014, v7.3.5</dt>
<dd>
- responsive design : gestion des images d'entête (petit oubli oops) via un JS qui se débrouille au chargement, <br>
- ajout d'un clear: left manquant sur les séparateurs,<br>
- musiques : ajout liens pour écouter les démo JeudiSoir et IYB
</dd>

<dt>09/08/2014, v7.3.2</dt>
<dd>
- pour une meilleure expérience sur mobiles et tablettes, responsive design sur les séparateurs
et le menu de navigation (via <a href="http://www.w3.org/TR/css3-mediaqueries/">Media Queries</a>
conjuguée à la <a href="http://www.w3.org/TR/mwabp/#bp-viewport">balise meta viewport</a>), <br>
- menu de navigation : basculé sur le nouvel élément <a href="http://www.w3.org/TR/html5/sections.html#the-nav-element">nav</a>,<br>
- menu de navigation : ajout de <a href="http://www.w3.org/TR/CSS21/generate.html">:before</a>
avec <a href="http://www.unicode.org/charts/PDF/U2700.pdf">U+27A6</a> pour les
séparations, <br>
- remise à jour de la rubrique Liens (reste encore pas mal de rédaction), <br>
- mise à jour contenu de la page Musiques,<br>
- corrections sur la lettre pi dans la description ci-dessus
</dd>

<dt>05/08/2014, v7.1.9</dt>
<dd>
- modif de <a href="zicmue/#piR_tromb">l'image dans musiques</a> (border, <a href="http://www.w3.org/TR/css3-background/#box-shadow">box-shadow</a> et <a href="http://www.w3.org/TR/css3-transforms/#funcdef-rotate">transform rotate</a>),<br>
- ajout d'un box-shadow sur les images de titre et les séparateurs,<br>
- ajout d'une image de titre pour <a href="moi/">la rubrique "moi"</a>,<br>
- ajout explications titre du site
</dd>

<dt>01/08/2014, v7.1.5</dt>
<dd>Continuation de la mise à niveau du site :<br>
- mise en sprites de certaines images (icones du menu de navigation, séparateurs),<br>
- menu de navigation : changement de certaines icones,<br>
- menu de navigation : modif du :hover, suppression d'un léger bug de décalage,<br>
- séparateurs : maintenant tirés au sort (un petit F5 pour voir ?),<br>
- séparateurs : ajout d'un séparateur X11,<br>
- séparateurs : ré-ordonnés différemment
</dd>

<dt>30/07/2014, v7.0.5</dt>
<dd>Ouf enfin ! Reprise de ce site... Bon, rien de trop visible mais c'est un début
de remise à niveau, avant d'attaquer le contenu...<br>
- doctype HTML5,<br>
- ajout de liens vers la home sur les titres de rubriques,<br>
- suppression des hacks IE (nous sommes - et ça fait du bien ! - dans une autre époque),<br>
- fusion des CSS (objectif moins de resources à télécharger),<br>
- remplacement des images des titres de 2eme niveau par du texte (vive les <a href="http://dev.w3.org/csswg/css-fonts/#font-face-rule">web fonts</a> !),<br>
- ré-écriture contenu page d'accueil,<br>
- ajout d'un favicon (oui, ça change tout ! ;) ) (et merci <a href="http://realfavicongenerator.net/">http://realfavicongenerator.net/</a>),<br>
- musiques : mini modif sur l'image,<br>
- musiques : ré-écriture et actualisation des groupes,<br>
- divers : ajout de liens,<br>
- liens : suppression du bookmark
</dd>

<dt>19/04/2009, v6.1.0</dt>
<dd>Correction et compléments dans l'article <a href="info/inet/html_ou_xhtml.php">"HTML ou XHTML ?"</a>
à propos de l'attribut id.
</dd>

<dt>26/02/2009</dt>
<dd>Suite aux <a href="http://groups.google.com/group/fr.comp.infosystemes.www.auteurs/msg/fce26086705e7a6a">remarques de Olivier Miakinen</a>
et parce que le temps passe :), quelques corrections sur l'article <a href="info/inet/html_ou_xhtml.php">"HTML ou XHTML ?"</a>.
</dd>

<dt>22/02/2009</dt>
<dd>- suppression rubrique Copains<br>
- mise à jour CV
</dd>

<dt>08/08/2007</dt>
<dd>Ouf ! repris enfin un peu de temps pour ce site...<br>
- "anonymisé" mon CV<br>
- mis en ligne les premières ébauches des documents web & charset plus complets<br>
- terminé le document <a href="info/inet/ND_doctype.php">Notes/Domino et Doctype</a></dd>

<dt>19/12/2006</dt>
<dd>Quelques mini modifications de quelques rédactionnels...</dd>

<dt>21/12/2005, v6.0.0</dt>
<dd>On a été sacrément occupé par le <a href="http://www.pingmachine.org">site de Ping Machine</a>
ces dernier temps, mais ça y est... à peu près !<br>
- Rajouté en section musique un petit barratin sur moi, et des pointeurs vers les coups de coeur blogés sur Ping Machine<br>
- Lien vers le site de Ping Machine (encore) dans la page des liens
</dd>

<dt>22/09/2005</dt>
<dd>- Ajout de Laetitia & Martial dans la page des copains<br>
- Corrections des articles <a href="info/inet/html_ou_xhtml.php">"HTML ou XHTML ?"</a>,
<a href="info/i18n/outils.php">"i18n Outils & doc"</a> et
<a href="info/i18n/web_charset.php">"Web, codages et jeux de caractères"</a><br>
- modif de la CSS (en particulier prb sur les blockquote)<br></dd>

<dt>24/08/2005</dt>
<dd>Modifications d'importance de la feuille de style principale, en espérant
que les pages soient maintenant plus lisibles<br>
Passage en ligne de la 1ere version complète de <a href="info/inet/html_ou_xhtml.php">HTML ou XHTML ?</a><br>
Et toujours en informatique, un nouveau document : <a href="info/inet/css_grp.php">CSS groupement de déclarations</a></dd>

<dt>08/08/2005</dt>
<dd>1ere version non en travaux de <a href="info/i18n/web_charset.php">web et codages</a></dd>

<dt>05/08/2005</dt>
<dd>Pleins de petites maj depuis un moment... Ce soir en particulier : quelques
petits mots pour se présenter sur cette page, une rubrique informatique qui
se remplit doucement (et même quelques articles terminés !!), la section
liens qui évolue doucement, la page copains qui se complète (tout aussi
doucement... oui bon), et pleins d'idées pour la rubrique musique !</dd>

<dt>14/07/2005</dt>
<dd>Après quelques modifs très techniques (CSS, balises LINK, ...) ou
mineures tout au long de la semaine dernière, passage en ligne d'une version
finale (pour la mise en page uniquement, chaque chose en son temps...) de la
page <a href="copains/">les copains</a> (d'abord)</dd>

<dt>22/06/2005</dt>
<dd>- prb du lien vers l'accueil dans le menu corrigé<br>
- page d'erreur 404 personnalisée<br>
- maquette compil 2001<br>
- Mise en place de IE7</dd>

<dt>17/06/2005</dt>
<dd>Mise en place de la majorité des images titres manquantes (<q>alors ça, c'est fait !</q>)<br>
"Liens dans nouvelle fenêtre" en position:fixed</dd>

<dt>22/05/2005</dt>
<dd>1ere mise à jour avec <a href="http://www.lyra.org/sitecopy/">Sitecopy</a> !<br>
Quelques modifs dans la page de liens, dans l'accueil, et ajout de quelques
images de titres niveau 2.</dd>

<dt>16/05/2005</dt>
<dd>Page de liens presque finale...</dd>

<dt>07/05/05</dt>
<dd>Bon j'avoue, perdre tout ce que j'avais réalisé jusqu'à maintenant dans mon
crash disque... Ca ne m'a pas aidé à m'y remettre. Après plusieurs mois de mise
en silence, nous y revoilà !! On a la gniaaak !! Bon, pour l'instant ce n'est
que l'accueil qui est à peu près OK. Par contre, les anciens auront remarqué
que les entrées du menu ont changées... car j'ai pleins d'idées !! Aller, j'y
retourne :))</dd>
