<?
/*******************************************************************************
 Intégration du code hightliter Highlight.js (https://highlightjs.org/)
 Version 20140813
*******************************************************************************/
?>
<link rel="stylesheet" href="http://cdnjs.cloudflare.com/ajax/libs/highlight.js/8.1/styles/sunburst.min.css">
<style>
.hljs
{
border-radius: 10px;
}
</style>
<script src="http://cdnjs.cloudflare.com/ajax/libs/highlight.js/8.1/highlight.min.js"></script>
<script>
hljs.initHighlightingOnLoad();
</script>