<link href="<?=$RelBasePath?>communs/zicmue_compils.css" rel="stylesheet" type="text/css">

<link rel="Contents" href="index.php">
<link rel="Chapter" href="compil_95.php" title="1995">
<link rel="Chapter" href="compil_96.php" title="1996">
<link rel="Chapter" href="compil_97.php" title="1997">
<link rel="Chapter" href="compil_98.php" title="1998">
<link rel="Chapter" href="compil_99.php" title="1999">
<link rel="Chapter" href="compil_00.php" title="2000">
<link rel="Chapter" href="compil_01.php" title="2001">
<link rel="Chapter" href="compil_02.php" title="2002">
<link rel="Chapter" href="compil_03.php" title="2003">
<link rel="Chapter" href="compil_04.php" title="2004">
<?if ($compil_AV != "") {?>
<link rel="Prev" href="compil_<?=$compil_AV?>.php">
<?}?>
<?if ($compil_AP != "") {?>
<link rel="Next" href="compil_<?=$compil_AP?>.php">
<?}?>

